[project]
name = "iadata700-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib",
    "seaborn",
    "pandas",
    "numpy",
    "pygments",
    "ipykernel",
    "scikit-learn>=1.9.1",
    "jupyter>=1.1.1",
]
